package io.ketill.hidusb;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.Objects;

public final class BlockedPeripheral<P> {

    public final @NotNull P peripheral;
    public final @Nullable Throwable cause;
    public final boolean unblockAfterDetach;

    BlockedPeripheral(@NotNull P peripheral, @Nullable Throwable cause,
                      boolean unblockAfterDetach) {
        this.peripheral = peripheral;
        this.cause = cause;
        this.unblockAfterDetach = unblockAfterDetach;
    }

    /* @formatter:off */
    @Override /* generated by IntelliJ IDEA */
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        BlockedPeripheral<?> that = (BlockedPeripheral<?>) o;
        return peripheral.equals(that.peripheral);
    }
    /* @formatter:on */

    /* @formatter:off */
    @Override /* generated by IntelliJ IDEA */
    public int hashCode() {
        return Objects.hash(peripheral);
    }
    /* @formatter:on */

    /* @formatter:off */
    @Override /* generated by IntelliJ IDEA */
    public String toString() {
        return "BlockedPeripheral{" +
                "peripheral=" + peripheral + ", " +
                "cause=" + cause + ", " +
                "unblockAfterDetach=" + unblockAfterDetach + "}";
    }
    /* @formatter:on */

}
